kind: Pod
apiVersion: v1
metadata:
  name: client-test
  namespace: saasglue-server-dev
spec:
  serviceAccountName: saasglue-service
  containers:
    - name: client-test
      image: client:v0.1.0
      command: ["sleep", "infinity"]
      imagePullPolicy: IfNotPresent
      env:
        - name: NODE_ENV
          value: dev_k8s
        - name: "PORT"
          value: "8080"
        - name: "SERVER_NAME"
          value: client
        - name: "API_PORT"
          value: "3000"
        - name: API_NAME
          value: server
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  restartPolicy: Never
  tolerations:
    - effect: NoSchedule
      key: duration
      operator: Equal
      value: static
    - effect: NoSchedule
      key: processorType
      operator: Equal
      value: cpu
