FROM node:16 as agent_deadletter_watcher

ARG DIR=/home/appuser
WORKDIR $DIR/app

ENV NODE_ENV production

COPY --from=server_base:v0.0.1 $DIR/app/server ./server
COPY --from=server_base:v0.0.1 $DIR/app/config ./config

RUN groupadd -g 999 appuser && \
  useradd -r -m -u 999 -g appuser -s /usr/sbin/nologin appuser

# Set restrictive permissions
RUN chmod -R 600 $DIR && \
  find $DIR -type d -exec chmod 700 '{}' \;

# Set ownership
RUN chown -R appuser:appuser $DIR

# Start application as unprivileged user
CMD runuser -u appuser -- "node" "./server/dist/RunServerWorkers.js"
