---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- if .Values.iamRoles }}
    {{- if .Values.iamRoles.agentDeadletterWatcherService }}
    eks.amazonaws.com/role-arn: {{ .Values.iamRoles.agentDeadletterWatcherService }}
    {{- end }}
    {{- end }}
  name: agent-deadletter-watcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saasglue-server.labels" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- if .Values.iamRoles }}
    {{- if .Values.iamRoles.schedulerService }}
    eks.amazonaws.com/role-arn: {{ .Values.iamRoles.schedulerService }}
    {{- end }}
    {{- end }}
  name: scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saasglue-server.labels" . | nindent 4 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- if .Values.iamRoles }}
    {{- if .Values.iamRoles.saaglueService }}
    eks.amazonaws.com/role-arn: {{ .Values.iamRoles.saaglueService }}
    {{- end }}
    {{- end }}
  name: saasglue-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saasglue-server.labels" . | nindent 4 }}
